[formatter.gofmt]
command = "gofmt"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]

[formatter.goimports]
command = "goimports"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]
