name: Build Binaries

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - name: build
        run: |
          nix develop --impure -c make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: legionlinuxtui
          path: build/legionlinuxtui

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: build/legionlinuxtui
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}