name: Build and Release Binaries

on:
  workflow_run:
    workflows:
      - Changlog
  workflow_dispatch:

env:
  BINARY-PATH: build/legionlinuxtui

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: build
        run: |
          nix develop --impure -c make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: legionlinuxtui
          path: ${{ env.BINARY-PATH }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          draft: false
          prerelease: false
          files: ${{ env.BINARY-PATH }}
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}